### ISSUE TITLE
launcher doesnt open

### ISSUE THREAD

**Issue by c9twoshot** [crocokyle/Valorant-Ultrawide-Fix#1]
i installed this per the instructions but after trying to open it via the new launcher it runs for half a second and closes and it never opens the launcher
[SysSetup_log.log](https://github.com/crocokyle/Valorant-Ultrawide-Fix/files/5862750/SysSetup_log.log)
[install_log.log](https://github.com/crocokyle/Valorant-Ultrawide-Fix/files/5862751/install_log.log)

these are the only logs i have available

**Comment by crocokyle** [comment]
Okay, everything looks okay in those log files. Could you right click on the launcher shortcut, select "Edit" and paste the contents of the launcher here?

**Comment by c9twoshot** [comment]
```bat
set LOGFILE=ValorantLauncher_log.log
call :LOG > %LOGFILE%
exit /B
:LOG
echo Patching Valorant screen resolution...
copy C:\Users\user\AppData\Local\VALORANT\Saved\Config\26fd0418-ff34-537c-b027-6400fb9ec9d2\Windows\GameUserSettingsSrc.ini C:\Users\user\AppData\Local\VALORANT\Saved\Config\26fd0418-ff34-537c-b027-6400fb9ec9d2\Windows\GameUserSettings.ini
echo Killing your Windows taskbar until game has closed...
echo Launching Valorant in Ultrawide
"C:\Riot Games\Riot Client\RiotClientServices.exe" --launch-product=valorant --launch-patchline=live
```

**Comment by crocokyle** [comment]
That all looks correct. Can you confirm that `RiotClientServices.exe` is in `C:\Riot Games\Riot Client\` ?

**Comment by c9twoshot** [comment]
yes i can confirm that it is

**Comment by crocokyle** [comment]
That's odd, okay could you try to right-click on your **original** Valorant shortcut, select properties, and paste the `Target:` value here? It should match up with the last line from your launcher:
```
"C:\Riot Games\Riot Client\RiotClientServices.exe" --launch-product=valorant --launch-patchline=live
```

**Comment by c9twoshot** [comment]
```
"C:\Riot Games\Riot Client\RiotClientServices.exe" --launch-product=valorant --launch-patchline=live
```

yea it appears that it does

**Comment by crocokyle** [comment]
Okay, something is going wrong with the launcher bat file execution I guess. Just as a test lets try to edit your launcher again and overwrite it with this code:

```bat
echo Patching Valorant screen resolution...
copy C:\Users\me\AppData\Local\VALORANT\Saved\Config\bd20b341-ef13-542a-bcf7-dc3523cc43c9\Windows\GameUserSettingsSrc.ini C:\Users\me\AppData\Local\VALORANT\Saved\Config\bd20b341-ef13-542a-bcf7-dc3523cc43c9\Windows\GameUserSettings.ini
echo Killing your Windows taskbar until game has closed...
echo Launching Valorant in Ultrawide
"C:\Riot Games\Riot Client\RiotClientServices.exe" --launch-product=valorant --launch-patchline=live
pause
```
This should give us a better output and stop it from closing before it gives you an error.

**Comment by crocokyle** [comment]
Okay, something is going wrong with the launcher bat file execution I guess. Just as a test lets try to edit your launcher again and overwrite it with this code:

```bat
echo Patching Valorant screen resolution...
copy C:\Users\user\AppData\Local\VALORANT\Saved\Config\26fd0418-ff34-537c-b027-6400fb9ec9d2\Windows\GameUserSettingsSrc.ini C:\Users\user\AppData\Local\VALORANT\Saved\Config\26fd0418-ff34-537c-b027-6400fb9ec9d2\Windows\GameUserSettings.ini
echo Killing your Windows taskbar until game has closed...
echo Launching Valorant in Ultrawide
"C:\Riot Games\Riot Client\RiotClientServices.exe" --launch-product=valorant --launch-patchline=live
pause
```
This should give us a better output and stop it from closing before it gives you an error.

**Comment by crocokyle** [comment]
Sorry, I originally commented with my directories. It is correct now

**Comment by c9twoshot** [comment]
Ok so it opened the game and I was able to play in ultrawide on Windowed mode but Fullscreen would default to 1080p this is what the CMD prompt says.

C:\Users\Sheena\Documents\ValorantUltrawideHack>∩╗┐echo Patching Valorant screen resolution...
'∩╗┐echo' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Sheena\Documents\ValorantUltrawideHack>copy C:\Users\Sheena\AppData\Local\VALORANT\Saved\Config\26fd0418-ff34-537c-b027-6400fb9ec9d2\Windows\GameUserSettingsSrc.ini C:\Users\Sheena\AppData\Local\VALORANT\Saved\Config\26fd0418-ff34-537c-b027-6400fb9ec9d2\Windows\GameUserSettings.ini
        1 file(s) copied.

C:\Users\Sheena\Documents\ValorantUltrawideHack>echo Killing your Windows taskbar until game has closed...
Killing your Windows taskbar until game has closed...

C:\Users\Sheena\Documents\ValorantUltrawideHack>echo Launching Valorant in Ultrawide
Launching Valorant in Ultrawide

C:\Users\Sheena\Documents\ValorantUltrawideHack>"C:\Riot Games\Riot Client\RiotClientServices.exe" --launch-product=valorant --launch-patchline=live

C:\Users\Sheena\Documents\ValorantUltrawideHack>pause
Press any key to continue . . .

**Comment by crocokyle** [comment]
Okay, it looks like adding logging to the launcher might have caused problems. I'm going to see if I can fix that. 

As far as the windowed mode goes, that is the workaround at the moment. It should appear as if it's in fullscreen (no borders or gaps), but it is going to render your desktop in parallel which will slightly reduce performance. It is a lightweight game so it shouldn't be too bad, but I should probably add a disclaimer for this in the readme. Unfortunately, that is the only method I could come up with without modified the binaries and tripping Vanguard.

**Comment by crocokyle** [comment]
Launcher logging should be fixed now in the releases.
