### ISSUE TITLE
Duplicate of #7 Taskbar on another monitor results in the wrong aspect ratio

### ISSUE THREAD

**Issue by crocokyle** [crocokyle/Valorant-Ultrawide-Fix#10]
I do have the same problem, could it be because of I (or we) have a monitor above the main one?
My logs:
[SysSetup_log.log](https://github.com/crocokyle/Valorant-Ultrawide-Fix/files/5921665/SysSetup_log.log)
[ValorantLauncher_log.log](https://github.com/crocokyle/Valorant-Ultrawide-Fix/files/5921667/ValorantLauncher_log.log)
[install_log.log](https://github.com/crocokyle/Valorant-Ultrawide-Fix/files/5921668/install_log.log)

_Originally posted by @Jugistyler in https://github.com/crocokyle/Valorant-Ultrawide-Fix/issues/8#issuecomment-772839881_

**Comment by crocokyle** [comment]
@Jugistyler when you run the Ultrawide Launcher, does the game start up on the correct monitor? Should have been monitor number 1 which has a resolution of `3440 x 1440`?

Also does your Windows Taskbar have autohide enabled or disabled?

**Comment by Jugistyler** [comment]
Yes, it has the correct monitor and resolution, and autohide is disabled.
![My monitor orientation](https://user-images.githubusercontent.com/54026602/108627399-0dab2580-745e-11eb-9056-f7584d7a2b4c.png)

**Comment by Mr-Stetson** [comment]
Yes, it starts in correct monitor and detects the correct resolutions. Taskbar Autohide is disabled. Here is my monitor orientation if it helps:
![Screenshot (2)](https://user-images.githubusercontent.com/54026602/108627476-72ff1680-745e-11eb-9a90-c84964c06b7e.png)

**Comment by crocokyle** [comment]
@Jugistyler Thanks for the screenshots. I'm starting to realize how important the taskbar position is to this script. not exactly sure why, but I'd be willing to bet that if you move the taskbar to the bottom of the monitor you want to play on, it will work properly. This is not a solution, but let me know if that works and I'll update #7 so I can work on this when I get time.

**Comment by crocokyle** [comment]
@Jugistyler I can confirm that placing the taskbar on another monitor causes this issue. It doesn't appear that there is an immediate fix for it. It seems like the entire script is dependent on the taskbar for some reason.  Since this and #7 are the same issue, I'm going to close this as a duplicate but feel free to check back or comment in #7 if that worked for you. I think the only workaround is to move your taskbar at the moment. 

Sorry, I know that's not a proper solution. This may go beyond my script and have more to do with Valorant itself, but I'll keep trying to find a workaround when I get some time.
