### ISSUE TITLE
Incorrect resolution detected

### ISSUE THREAD

**Issue by swigity** [crocokyle/Valorant-Ultrawide-Fix#11]
I don't have any old installations of valorant and I don't have auto hide but it still has the same black bars on the sides of the screen.

**Comment by crocokyle** [comment]
Can you post the logs from your installation here? Also, is your taskbar located on the same monitor you want to play on?

**Comment by swigity** [comment]
> Can you post the logs from your installation here? Also, is your taskbar located on the same monitor you want to play on?

I only have one monitor so the taskbar is on the same monitor I play on. I tried finding the logs but in documents in file explorer I couldn't find any folder called ValorantUltrawideHack or anything of the sorts.

**Comment by crocokyle** [comment]
Some people have reported similar issues when they have multiple drives and their `Documents` or `User` folder is located on a separate drive (or volume) from the OS. 

Try extracting the zip file to your desktop and running the installer from there. You can also check to see if it might have created a new `/users/<yourusername>/Documents/ValorantUltrawideHack` in your OS volume if it is separate from where your other libraries are stored.

**Comment by swigity** [comment]
Ok thank you that did work, it was in my user documents folder. 
I have install log, I have SysSetup log, and I have ValorantLauncher log. How should I post it? Should I post a screenshot or should I copy and paste the logs?

**Comment by crocokyle** [comment]
You can just drag and drop the files into a comment here or paste them as code blocks. Either is fine.

**Comment by swigity** [comment]
[install_log.log](https://github.com/crocokyle/Valorant-Ultrawide-Fix/files/6018433/install_log.log)
[SysSetup_log.log](https://github.com/crocokyle/Valorant-Ultrawide-Fix/files/6018434/SysSetup_log.log)
[ValorantLauncher_log.log](https://github.com/crocokyle/Valorant-Ultrawide-Fix/files/6018435/ValorantLauncher_log.log)

**Comment by crocokyle** [comment]
Is your monitor's native resolution `2293 x 960` or do you have any scaling enabled?

Also, I know you said your taskbar is on the main monitor, but just wondering if it is located on the bottom of the screen?

**Comment by swigity** [comment]
no my monitors resolution is 3440 by 1440. I don't have any scaling enabled.

**Comment by crocokyle** [comment]
Okay, I think that is the problem. I'm not sure why but the script is detecting your resolution as `2293 x 960`. 

The quick fix would be to open the file:
 `C:\Users\manus\AppData\Local\VALORANT\Saved\Config\1db54cac-6a49-5612-a94d-b0593352fce4\Windows\GameUserSettingsSrc.ini`
 in notepad. 

**Make sure you open `GameUserSettingsSrc.ini` NOT `GameUserSettings.ini`**

Use find and replace by pressing `CTRL+H` and replace all instances of `2293` with `3440` and replace all instances of `960` with `1440`. Save the file and you should be good to test it. 

It's hard to say why the script is detecting the wrong resolution for your system, but it usually has to do with display mods, taskbar, graphics scaling, or accessibility settings.

**Comment by swigity** [comment]
Yaaaayyyy it worked! Thank you so much for going out of your way to help!

**Comment by crocokyle** [comment]
Okay, great! glad to help
